landing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from .views import home

urlpatterns = [
    path('', home, name='home'),
    path('accounts/login/', auth_views.LoginView.as_view(
        template_name='login.html', redirect_field_name=''), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(
        next_page='/accounts/login/'), name='logout'),
    path('admin/', admin.site.urls),
    path('user/', include('userprofile.urls')),
    path('', include('management.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    # path('', views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('testimonial', views.testimony, name='testimony'),
    path('about-us', views.about, name='about'),
    #path('register', views.register, name='register'),
    #path('login', views.login_user, name='login'),
    path('team', views.team, name='team'),
    path('<int:team_id>/team', views.team_member, name='team_member'),
    path('lecturers', views.lecturers, name='lecturers'),
    path('<int:lecturer_id>/lecturer', views.lecturer, name='lecturer'),
    path('gallery', views.gallery, name='gallery'),
    path('facilities', views.facilities, name='facilities'),
    #path('logout', views.logout_user, name='logout'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('contact', views.contact, name='contact'),
    path('register', views.register, name='register'),
    path('profile', views.profile, name='profile'),
    path('profileupdate', views.profileupdate, name='profileupdate'),
]

userprofile/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.db.models.signals import post_save, pre_save


import datetime


class Examination(models.Model):
    name = models.CharField(max_length = 20)
    description = models.TextField()
    picture = models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')

    def __str__(self):
        return self.name


class Level(models.Model):
    name = models.CharField(max_length = 20)
    abbr = models.CharField(max_length = 10)
    rank = models.IntegerField(unique = True)
    exam = models.ForeignKey(Examination, on_delete=models.CASCADE)
    no_courses = models.IntegerField(default = 1)

    class Meta:
        unique_together = ('name', 'rank', 'exam')

    def __str__(self):
        return self.name


class Course(models.Model):
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    name = models.CharField(max_length = 20)
    abbr = models.CharField(max_length=10)

    def __str__(self):
        return self.name



class UserProfile(models.Model):
    SEX = (
        ('F', 'female'),
        ('M', 'male'),
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    passport = models.ImageField(upload_to="photos/%Y/%m/%d", help_text=("Maximum of 1mb.(100x100px)"))
    surname = models.CharField(max_length = 250)
    other_names = models.CharField(max_length = 250)
    reg_no = models.CharField(max_length = 20)
    email = models.EmailField()
    sex = models.CharField(max_length=1, choices=SEX)
    phone = models.CharField(max_length = 13)
    employers_name = models.CharField(max_length =50)
    contact_address = models.TextField()
    contacts_details = models.TextField(
        "In case of emergency, contact person NAME, ADDRESS, PHONE")
    institutions = models.TextField("Schools attended till date")
    exam = models.ForeignKey(Examination, on_delete=models.PROTECT)
    last_level = models.ForeignKey(
        Level, on_delete=models.PROTECT, related_name='last_level', 
        verbose_name="Last level passed/exempted")
    date_passed = models.DateField(verbose_name ="Date last level was passed/exempted")
    current_level = models.ForeignKey(
        Level, on_delete=models.PROTECT, related_name='current_level', 
        verbose_name="Level to be attempted")
    exam_date = models.DateField(verbose_name ="Expected date of coming exam")
    courses = models.ManyToManyField(Course)
    sponsor = models.CharField(max_length = 250)
    sponsor_signature = models.ImageField(
        upload_to="photos/%Y/%m/%d", help_text=("Maximum of 1mb.(100x100px)"))
    reg_date = models.DateTimeField(auto_now_add = True)
    paid = models.BooleanField(default=True)

    def __str__(self):
        return self.user
    

class PaymentStructure(models.Model):
    examination = models.ForeignKey(Examination, on_delete=models.CASCADE)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    registration = models.PositiveIntegerField(help_text='Registration Fee')
    base_fee = models.PositiveIntegerField()
    course_fee = models.PositiveIntegerField(help_text='Fee Per Course')

    class Meta:
        unique_together = ('examination', 'level')

    def __str__(self):
        return str(self.level)



class RegistrationFee(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    amount_paid = models.PositiveIntegerField()
    payment_date = models.DateField()
    teller_no = models.CharField(max_length=10)
    balance = models.PositiveIntegerField()

    def __str__(self):
        return self.user


class TuitionFee(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    amount_paid = models.PositiveIntegerField()
    payment_date = models.DateField()
    teller_no = models.CharField(max_length=10)
    balance = models.PositiveIntegerField()

    def __str__(self):
        return str(self.user)

userprofile/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import UserProfile, Examination, RegistrationFee, TuitionFee


YEAR_CHOICES = ('2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', 
    '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024')

class UserForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Re-type Password', widget=forms.PasswordInput)
    #email = forms.EmailField()
    username = forms.CharField(label='Email', error_messages = {'unique': 'A user with that Username already exists, '
        'try another'
            })
    
    class Meta:
        model = User
        
        fields = ['username', 'password1', 'password2']
    
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("The Passwords don't match")
        return password2


class ProfileForm(forms.ModelForm):
    date_passed = forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.DateInput(attrs={
        'type': 'date',
        'placeholder': 'dd/mm/yy'
    }))
    exam_date = forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.DateInput(attrs={
        'type': 'date',
        'placeholder': 'dd/mm/yy'
    }))
    #email=(widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    
    class Meta:
        model = UserProfile
        exclude = ['user', 'reg_date', 'email', 'paid']     

     # ['username', 'email', 'password1', 'password2','passport',
     #     'other_names', 'reg_no', 'empoyers_name', 'contact_address', 'contacts_details', 'exam',
     #      'last_level', 'date_passed', 'current_level', 'exam_date', 'courses', 'sponsor', 
     #      'sponsor_signature', 'institutions', 'surname', 'phone']

    def clean_phone(self):
        # Check that phone number is valid
        phone = self.cleaned_data.get("phone")
        if phone:
            try:
                int(phone) + 1
            except Exception as e:
                raise forms.ValidationError("Invalid Phone Number")
        return phone

    def clean_passport(self):
        passport = self.cleaned_data.get('passport',None)
        if not passport:
            raise forms.ValidationError("Couldn't read uploaded image")
        # if passport._height < 50 or passport._width < 50:
        #     raise forms.ValidationError("Photo dimensions are too small (minimum 50X50 )")
        if passport._size > 1*1024*1024:
            raise forms.ValidationError("Image file too large (1mb max )")

        return passport


class RegFeeForm(forms.ModelForm):
    payment_date = forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.DateInput(attrs={
        'type': 'date',
        'placeholder': 'dd/mm/yy'
    }))
    class Meta:
        model = RegistrationFee
        exclude = ('user', 'balance')


class TuiFeeForm(forms.ModelForm):
    payment_date = forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.DateInput(attrs={
        'type': 'date',
        'placeholder': 'dd/mm/yy'
    }))
    class Meta:
        model = TuitionFee
        exclude = ('user', 'balance')



class SubjectForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('courses',)

    def clean(self):
        cleaned_data = super(SubjectForm, self).clean()
        courses = cleaned_data.get("courses")
        if courses:
            s = courses[0]
            exam = s.level
            count = 0
            for sub in courses:
                count += 1
            if count > exam.subjects:
                raise forms.ValidationError("You can't choose above the required number of subjects")



class UpdateProfileForm(forms.ModelForm):
    #examination = forms.ModelChoiceField(queryset=Examination.objects.filter(active=True), widget=forms.Select())

    class Meta:
        model = UserProfile
        fields = ('email', 'phone', 'passport')


    def clean_phone(self):
        # Check that phone number is valid
        phone = self.cleaned_data.get("phone")
        if phone:
            try:
                int(phone) + 1
            except Exception as e:
                raise forms.ValidationError("Invalid Phone Number")
        return phone


    def clean_passport(self):
        # Check that passport is valid
        picture = self.cleaned_data.get("passport",None)
        if not picture:
            raise forms.ValidationError("Couldn't read uploaded image")
        if picture.size > 250*1024:
            raise forms.ValidationError("Image file too large (250kb max)")
        if picture.size < 25*1024:
            raise forms.ValidationError("Image file too small (25kb min)")
        return picture

userprofile/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render#, render_to_response
from django.http import HttpResponseRedirect
from django.contrib import messages # add context to HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils import timezone

from userprofile.models import UserProfile
from userprofile.forms import (UserForm, ProfileForm, RegFeeForm, 
	TuiFeeForm, UpdateProfileForm)

# Create your views here.

def contact(request):
	pass


def register(request):
	CURRENTYEAR = timezone.now().today().year
	if request.method == 'POST':
		uform = UserForm(request.POST)
		pform = ProfileForm(request.POST, request.FILES)
		rform = RegFeeForm(request.POST)
		tform = TuiFeeForm(request.POST)
		if uform.is_valid() and pform.is_valid() and rform.is_valid() and tform.is_valid():
			user = uform.save(commit=False)
			username = uform.cleaned_data['username']
			password = uform.cleaned_data['password1']
			#email = uform.cleaned_data['email']
			user.set_password(password)
			user.email = username
			user.save()
			passport = pform.cleaned_data['passport']
			surname = pform.cleaned_data['surname']
			other_names = pform.cleaned_data['other_names']
			reg_no = pform.cleaned_data['reg_no']
			sex = pform.cleaned_data['sex']
			phone = pform.cleaned_data['phone']
			employers_name = pform.cleaned_data['employers_name']
			contact_address = pform.cleaned_data['contact_address']
			contacts_details = pform.cleaned_data['contacts_details']
			institutions = pform.cleaned_data['institutions']
			exam = pform.cleaned_data['exam']
			last_level = pform.cleaned_data['last_level']
			date_passed = pform.cleaned_data['date_passed']
			current_level = pform.cleaned_data['current_level']
			exam_date = pform.cleaned_data['exam_date']
			sponsor = pform.cleaned_data['sponsor']
			sponsor_signature = pform.cleaned_data['sponsor_signature']
			courses = pform.cleaned_data['courses']
			# user = authenticate(username=username, password=password)
			# if user is not None:
			#     if user.is_active:
			#         login(request, user)
			# userprofile = pform.save(commit=False)
			userprofile, created = UserProfile.objects.get_or_create(user=user)
			userprofile.email = username
			userprofile.passport = passport
			userprofile.surname = surname
			userprofile.other_names = other_names
			userprofile.reg_no = reg_no
			userprofile.sex = sex
			userprofile.phone = phone
			userprofile.employers_name = employers_name
			userprofile.contact_address = contact_address
			userprofile.contacts_details = contacts_details
			userprofile.institutions = institutions
			userprofile.exam = exam
			userprofile.last_level = last_level
			userprofile.date_passed = date_passed
			userprofile.current_level = current_level
			userprofile.exam_date = exam_date
			userprofile.sponsor = sponsor
			userprofile.sponsor_signature = sponsor_signature
			for i in courses:
				userprofile.courses.add(i)
			userprofile.save()

			regfee = rform.save(commit=False)
			regfee.user = userprofile
			regfee.save()
			tuifee = tform.save(commit=False)
			tuifee.user = userprofile
			tuifee.save()

			messages.add_message(request, messages.INFO, 
			"Registration Successful! Please Login")
			return HttpResponseRedirect('/login/')
			
		else:
			# uform = UserForm()
			# pform = ProfileForm()
			context_instance = {'uform': uform, 'pform': pform, 'CURRENTYEAR':CURRENTYEAR,
			'rform': rform, 'tform': tform, 'error_message': 'Invalid Registration!'}
			return render(request, 'userprofile/register.html', context_instance)
	else:
		uform = UserForm()
		pform = ProfileForm()
		rform = RegFeeForm()
		tform = TuiFeeForm()
		context_instance = {'uform': uform, 'pform': pform, 'rform': rform, 'tform': tform, 'CURRENTYEAR':CURRENTYEAR}
		return render(request, 'userprofile/register.html', context_instance)


def profile(request):
	CURRENTYEAR = timezone.now().today().year
	userprofile = UserProfile.objects.get(user=request.user)
	context_instance={'userprofile':userprofile, 'CURRENTYEAR':CURRENTYEAR,
	'error_message': ''}
	return render(request, 'userprofile/profile.html', context_instance)


def profileupdate(request):
    if request.user.is_authenticated() and not request.user.is_staff:
        try:
            userprofile = UserProfile.objects.get(user=request.user)
            if userprofile.paid:
                pform = UpdateProfileForm(request.POST or None, request.FILES or None, instance=userprofile)
               # sform = SubjectForm(request.POST or None, instance=userprofile)
                if request.method == 'POST':
                    if pform.is_valid():# and sform.is_valid():
                        pform.save()
                        #sform.save()
                        return HttpResponseRedirect('/user/profile/')
                context_instance={'pform': pform, 'userprofile':userprofile}
                return render(request, 'userprofile/update_profile.html', context_instance)
            else:
                logout(request)
                messages.add_message(request, messages.INFO, 
                "Your Payment Has Not Been Confirmed. Please Check Back Or Make Payment If You Have Not")
                return HttpResponseRedirect('/login/')
        except UserProfile.DoesNotExist:
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/login/')

userprofile/templates/userprofile/profile.html
{% extends 'user_base.html' %}

{% load static %}
{% block css %}<link href="{% static 'general/profile.css' %}" rel="stylesheet" media="screen">{% endblock %}

{% block title %}{{ userprofile.first_name }}{% endblock %}

{% block main %}
  <section>
    <div class="container">
      <div>
        {% if error_message %}
          <p><strong>{{ error_message }}</strong></p>
        {% endif %}
      </div>
      <div class="col-sm-4 col-md-4">
        <div>
          <div>
            <br>
            <h4>Welcome {{ userprofile.other_names }}</h4>
            <br>
            <p>
              <a href="{% url 'userprofile:profile' %}" class="page-scroll btn btn-xl" style="width: 100%;">Profile</a>
            </p>
            <p>
              <a href="{% url 'userprofile:profileupdate' %}" class="page-scroll btn btn-xl" style="width: 100%;">Update Profile</a>
            </p>
            <p>
              <a href="#" class="page-scroll btn btn-xl" style="width: 100%;">Download Resources</a>
            </p>
            <br><br>
            
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-md-6">
        <div>
          <div>
            <div class="details">
              {% block box %}
              <label>
                Registration No.:
              </label><br>
              {{ userprofile.reg_no }}<br><br>
              <label>
                NAME:
              </label><br>
              {{ userprofile.surname|upper }}, {{ userprofile.other_names|upper }}
              <br>
              <label>
                Phone Number:
              </label><br>
              {{ userprofile.phone }}<br>
              <label>
                Sex:
              </label><br>
              {{ userprofile.sex }}<br><br>
              
              {% if userprofile.user.username == userprofile.email %}
              <label>
                Email:
              </label><br>
              {{ userprofile.email }}<br><br>
              {% else %}
              <label>
                Login Email:
              </label><br>
              {{ userprofile.user.username }}<br><br>
              <label>
               Updated Email:
              </label><br>
              {{ userprofile.email }}<br><br>
              {% endif %}
              <label>
                Examination:
              </label><br>
              {{ userprofile.exam }}
              <br>
              <label>
                Registered Courses:
              </label><br>
              <ul>
              {% for sub in userprofile.courses.all %}
              <li>{{ sub.name }}</li>
              {% endfor %}
              </ul>
              <br>
              {% endblock %}
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-2 col-md-2">
        <div>
          <div>
            <h3>
            <label>
              Passport Photo: 
            </label>
            </h3>
            <br>
            <img src="{{ userprofile.passport.url }}" class="img-responsive" style="width: 100px; float: left; margin-right: 10px;" /><br><br>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

userprofile/templates/userprofile/register.html
{% extends 'base.html' %}

{% load static %}

{% block main %}
<section id="join-us">
<div id="enrol">
    <div class="row">
        <div class="col-sm-6 col-md-8 col-md-offset-2">
            <h1 class="text-center login-title">Enrolment Form</h1>
            <div class="account-wall">
                <!-- Error messaging -->
              <div id="errors">
                <div class="inner">
                  <ul>    
                  {% if uform.errors %}
                    <em>Please correct the following:</em>
                    <li class="text-danger small">{{ uform.non_field_errors }}</li>
                    {% for field in uform %}
                      {% if field.errors %}<li class="text-danger small">{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                    {% endfor %}
                  {% endif %}
                  {% if pform.errors %}
                    <li class="text-danger small">{{ pform.non_field_errors }}</li>
                    {% for field in pform %}
                      {% if field.errors %}<li class="text-danger small">{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                    {% endfor %}
                  {% endif %}
                  {% if rform.errors %}
                    <li class="text-danger small">{{ rform.non_field_errors }}</li>
                    {% for field in rform %}
                      {% if field.errors %}<li class="text-danger small">{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                    {% endfor %}
                  {% endif %}
                  {% if tform.errors %}
                    <li class="text-danger small">{{ tform.non_field_errors }}</li>
                    {% for field in tform %}
                      {% if field.errors %}<li class="text-danger small">{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                    {% endfor %}
                  {% endif %}
                  </ul>
                  <span class="text-danger small"> {{ error_message}}</span>
                </div>
              </div> 
              <!-- /Error messaging -->
              <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
                {% for field in uform %}
                <div >
                  <label class="control-label">{{ field.label_tag }}</label>
                  <div >{{ field }}</div>
                  <div >
                    <span class="helptext">{{ field.help_text }}</span>
                  </div>
                </div>
                {% endfor %}
                {% for field in pform %}
                <div>
                  <label class="control-label">{{ field.label_tag }}</label>
                  <div >{{ field }}</div>
                  <div >
                    <span class="helptext">{{ field.help_text }}</span>
                  </div>
                </div>
                {% endfor %}
                <h4>Registration Fee</h4>
                {% for field in rform %}
                <div>
                  <label class="control-label">{{ field.label_tag }}</label>
                  <div >{{ field }}</div>
                  <div >
                    <span class="helptext">{{ field.help_text }}</span>
                  </div>
                </div>
                {% endfor %}
                <h4>Tuition Fee</h4>
                {% for field in tform %}
                <div>
                  <label class="control-label">{{ field.label_tag }}</label>
                  <div >{{ field }}</div>
                  <div >
                    <span class="helptext">{{ field.help_text }}</span>
                  </div>
                </div>
                {% endfor %}
                <br/>
              <button class="btn btn-lg btn-primary" type="submit">
                  Submit</button> &nbsp;
                  <br/>
              <a href="{% url 'login' %}" class="need-help">Login here</a>
              </form>
              <br/>
            </div>
            <a href="{% url 'management:contact' %}" class="pull-right text-center new-account">Need help? </a><span class="clearfix"></span>
            <br/>
          </div>
    </div>
</div>
</section>
{% endblock %}

userprofile/templates/userprofile/update_profile.html
{% extends 'userprofile/profile.html' %}

{% load static %}
{% block css %}
<link href="{% static 'mngr/profile.css' %}" rel="stylesheet" media="screen">
<!-- jQuery -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
{% endblock %}

{% block title %}{{ userprofile.first_name }}{% endblock %}

{% block box %}
	<section>
		<div style="width: 95%;">
			<div class="col-xs-12 col-md-12">
				<div>
					<div>
						<h3>Edit Profile</h3>
						<!-- Error messaging -->
						<div id="errors">
							<div class="inner">
								<ul>
								{% if pform.errors %}
									<li class="text-danger small">{{ pform.non_field_errors }}</li>
									{% for field in pform %}
										{% if field.errors %}<li class="text-danger small">{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
									{% endfor %}
								{% endif %}
								</ul>
							</div>
						</div> 
						<!-- /Error messaging -->
						
						<form style="width: 100%; margin: 2%;" class="form-horizontal" action="" method="post" enctype="multipart/form-data">
							{% csrf_token %}
							{% for field in pform %}
								<div class="form-group">
									<label class="control-label col-sm-4">{{ field.label_tag }}</label>
									<div class="col-sm-3" style="width: 100%;">{{ field }}</div>
									<div class="col-sm-5">
										<span style="font-size:0.5625em;line-height:0.9375em;" class="helptext">{{ field.help_text }}</span>
									</div>
								</div>
							{% endfor %}
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<button type="submit" class="btn btn-success">Submit</button>
								</div>
							</div>
						</form>

					</div>
				</div>
			</div>

		</div>
	</section>
{% endblock %}