landing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from .views import home

urlpatterns = [
    path('', home, name='home'),
    path('accounts/login/', auth_views.LoginView.as_view(
        template_name='login.html', redirect_field_name=''), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(
        next_page='/accounts/login/'), name='logout'),
    path('admin/', admin.site.urls),
    path('user/', include('userprofile.urls')),
    path('', include('management.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    # path('', views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('testimonial', views.testimony, name='testimony'),
    path('about-us', views.about, name='about'),
    #path('register', views.register, name='register'),
    #path('login', views.login_user, name='login'),
    path('team', views.team, name='team'),
    path('<int:team_id>/team', views.team_member, name='team_member'),
    path('lecturers', views.lecturers, name='lecturers'),
    path('<int:lecturer_id>/lecturer', views.lecturer, name='lecturer'),
    path('gallery', views.gallery, name='gallery'),
    path('facilities', views.facilities, name='facilities'),
    #path('logout', views.logout_user, name='logout'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('contact', views.contact, name='contact'),
    path('register', views.register, name='register'),
    path('profile', views.profile, name='profile'),
    path('profileupdate', views.profileupdate, name='profileupdate'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">
    <!-- <link type="text/css" rel="stylesheet" href="{% static 'css/vendor.css' %}"> -->
    <link rel="shortcut icon" href="{% static 'images/company/favicon.png' %}" />
    <title>
        {% block title %}
        {% endblock %}-LegacyTutors
    </title>
    <meta name="theme-color" content="#0291e6" />
</head>
<body>
    <div class="container">
        <header id="header">
            <div id="the_brand">
                <a class="company" href="{% url 'home' %}">
                    <img src="{% static 'images/company/logo.png' %}" id="header-img" />
                    <h1>-LegacyTutors</h1>
                </a>
            </div>
            <div class="Navbar__Link Navbar__Link-toggle">
              MENU
            </div>
            <nav id="nav-bar" class="nav-items">
                    <div class="nav-link">
                      <a href="{% url 'userprofile:register' %}">
                        Students
                      </a>
                    </div>
                    <div class="nav-link">
                      <a href="{% url 'management:testimony' %}">
                        Testimonials
                      </a>
                    </div>
                    <div class="nav-link">
                      <a href="{% url 'management:lecturers' %}">
                        Lecturers
                      </a>
                    </div>
                    <div class="nav-link">
                      <a href="{% url 'management:about' %}">
                        About Us
                      </a>
                    </div>
                    <div class="nav-link">
                      <a href="{% url 'management:gallery' %}">Gallery</a>
                    </div>
                    <div class="nav-link {% block contact_active %}{% endblock %}">
                        <a class="page-scroll" href="{% url 'management:contact' %}">
                          CONTACT
                        </a>
                    </div>
            </nav>
        </header>
        <main>
            {% block main %}
            {% endblock %}
        </main>
        <footer>Copyright <a href="#">Legacy Tutors 2020</a> | Powered by: <a target="_blank" href="https://diamantemine.com/">DML</a></footer>
    </div>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script> -->
    <!-- <script src="{% static 'js/plugins.js' %}"></script>
    -->
    <script>
      /* menu toggle
   * ------------------------------------------------------ */
   function menuToggle() {
    const navs = document.querySelectorAll('.nav-items')
  
    navs.forEach(nav => nav.classList.toggle('Navbar__ToggleShow'));
  }

    document.querySelector('.Navbar__Link-toggle')
      .addEventListener('click', menuToggle);
</script>

</body>
</html>

templates/based.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
     <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>LegacyTutors - {% block title %}Home{% endblock %}</title>

    <!-- Loads the path to static files -->
    {% load static %}
    <link rel="icon" href="{% static 'images/logo.png' %}" />

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'owl/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'owl/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'general/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/simplePagination.css' %}">
    {% block css %}{% endblock %}
    
    <!-- Optional theme -->
<!--     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
 -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="{% static 'general/main.css' %}">

    <meta name="theme-color" content="#0291e6" />
  </head>
  <body>
    <!-- Header Start -->
    <header>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <!-- header Nav Start -->
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Menu</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="index.html">
                    <img src="{% static 'images/logo1.png' %}" alt="LegacyTutors">
                  </a>
                </div>
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                      <li class="{% block home_active %}{% endblock %}">
                          <a class="page-scroll" href="{% url 'general:index' %}">
                              <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                          </a>
                      </li>
                      <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; 
                          Students
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                          <li><a href="{% url 'userprofile:register' %}">Register</a></li>
                          <li><a href="{% url 'login' %}">Login</a></li>
                        </ul>
                      <li>
                        <a href="{% url 'general:testimony' %}">
                          <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>&nbsp; Testimonials
                        </a>
                      </li>
                      <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                          <span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp; 
                          About Us
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                          <li><a href="{% url 'general:about' %}">Who We Are</a></li>
                          <li><a href="{% url 'general:team' %}">Our Team</a></li>
                          <li><a href="{% url 'general:lecturers' %}">Lecturers</a></li>
                          <li><a href="{% url 'general:facilities' %}">Facilities</a></li>
                          <li><a href="{% url 'general:gallery' %}">Gallery</a></li>
                        </ul>
                      </li>
                      <li class="{% block contact_active %}{% endblock %}">
                          <a class="page-scroll" href="{% url 'general:contact' %}">
                              <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp; CONTACT
                          </a>
                      </li>
                    </ul>
                  </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
              </nav>
            </div>
          </div>
        </div>
      <div>
        <marquee>
          <strong style="color:#5e1a1a; font-size:2em;">
              We have been inundated with calls from prospective students, former students and other well 
              wishers reporting some people misrepresenting LEGACY TUTORS via some phone numbers purportedly gotten online. 
              While we are working on getting the identity of such miscreants and reporting them to the relevant authorities 
              we can confirm to you that the following numbers are the only phone contacts of LEGACY TUTORS: 0708 754 4904, 
              0703 891 7831 and 0802 322 6913. 
              You can also visit us on www.legacytutors.com or send us email on legacyassociates@ymail.com
              NB: Please do well to report to us; any such number or persons misrepresenting our noble Tuition Centre. Thank you
            </strong>
        </marquee>
      </div>
      </header><!-- header close -->
  {% block body %}

  {% endblock %}
  

   <!-- footer Start -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="footer-menu">
              <ul>
                <li>
                  <a href="#"><span class="fa fa-linkedin" aria-hidden="true"></span>&nbsp;</a>
                </li>
                <li>
                  <a href="https://www.instagram.com/legacytutors"><span class="fa fa-instagram" aria-hidden="true"></span>&nbsp;</a>
                </li>
                <li>
                  <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span>&nbsp;</a>
                </li>
                <li>
                  <a href="https://www.facebook.com/legacy.tutors.3/#"><span class="fa fa-facebook" aria-hidden="true"></span>&nbsp;</a>
                </li>
              </ul>
            </div>
            <p>LegacyTutors 2017-<script>document.write(new Date().getFullYear())</script> &copy;  by <a href="http://diamantemine.org/">DML</a>.</p>
          </div>
        </div>
      </div>
    </footer>
    

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/0.1.12/wow.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'owl/owl.carousel.min.js' %}"></script>
    <script src="{% static 'general/main.js' %}"></script>
    <script src="{% static 'css/jquery.simplePagination.js' %}"></script>
    {% block script %}{% endblock %}

    

  </body>
</html>

templates/csrf.html
<!DOCTYPE html>
<html>
<head>
	<title>LegacyTutors</title>
</head>
<body>

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% endblock %}
{% block header %}
{% endblock %}

{% block main %}
<style>
#welcome-section {
    /* background: linear-gradient(rgba(42,40,108, 0.4), rgba(42,40,108, 0.4)), url("{% static 'images/company/Flier.jpg' %}"); */
    background: linear-gradient(rgba(42,40,108, 0.4), rgba(42,40,108, 0.4)), url("{% static 'images/company/legacy-compd2.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
}
</style>
<section id="welcome-section">
    <h1 id="intro">...we take you to The Promised Land</h1>
</section>

<section id="events">
    <h3>Professional Examinations</h3>
    <div id="show-case">
        <div class="show-case">
            <figure>
                <img  class="img-fluid" src="{% static 'images/Flier.jpg' %}" alt="flier">
                <figcaption>&nbsp;</figcaption>
            </figure>
        </div>
        <div class="show-case">
            <figure>
                <img class="img-fluid" src="{% static 'images/atswa.png' %}" alt="ATSWA">
                <figcaption>
                    ATSWA
                    {{atswa.description}}
                </figcaption>
            </figure>
        </div>
        <div class="show-case">
            <figure>
                <img class="img-fluid" src="{% static 'images/ican1.png' %}" alt="ICAN">
                <figcaption>
                    ICAN
                    {{ican.description}}
                </figcaption>
            </figure>
        </div>
        <div class="show-case">
            <figure>
                <img class="img-fluid" src="{% static 'images/acca.jpg' %}" alt="ACCA">
                <figcaption>
                    ACCA
                    {{acca.description}}
                </figcaption>
            </figure>
        </div>
        <div class="show-case">
            <figure>
                <img class="img-fluid" src="{% static 'images/citn.png' %}" alt="CITN">
                <figcaption>
                    CITN
                    {{citn.description}}
                </figcaption>
            </figure>
        </div>
    </div>
</section>
<section id="testimonials">
    <h3>WHAT CUSTOMERS ARE SAYING</h3>
    <div class="about">
        {% for i in testis %}
        <div class="about-item">
            <h4>{{ i.name }}</h4>
            <p>{{ i.testimonial }}</p>
        </div>
        {% endfor %}
    </div>
    <br/>
    <div>
        <a href="{% url 'management:testimony' %}">View More</a>
    </div>
    
</section>

{% endblock %}

templates/login.html
{% extends 'general/base.html' %}

{% load static %}

{% block body %}
<section id="login2">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block">
        </div>
      </div>
    </div>
    <div class="arrow">
      <h1><a class="animated bounceInDown"  data-wow-delay="50s">LOGIN</a></h1>
    </div>
  </div>
</section>
<div class="container login">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <h1 class="text-center login-title">Log In To Your Account</h1>
            <div class="account-wall">
                <img class="profile-img" src="{% static 'images/person.png' %}"
                    alt="">
                <!-- Error messaging -->
                  <div id="errors">
                    <div class="inner">
                      <ul>    
                      {% if form.errors %}
                        <em>Please correct the following:</em>
                        <li class="text-danger small">{{ form.non_field_errors }}</li>
                        {% for field in form %}
                          {% if field.errors %}<li class="text-danger small">{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                        {% endfor %}
                      {% endif %}
                      </ul>
                      <span class="text-danger small"> {{ error_message}}</span>
                    </div>
                  </div> 
                  {% if messages %}
                    <ul class="text-danger messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %} class="text-danger small">{{ message }}</li>
                        {% endfor %}
                    </ul>
                  {% endif %}
                  <!-- /Error messaging -->
                <form class="form-signin" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                <input name="username" type="text" class="form-control" placeholder="Email" required autofocus>
                <input name="password" type="password" class="form-control" placeholder="Password" required>
                <button class="btn btn-lg btn-primary" type="submit">
                    Log in</button>
                <a href="{% url 'userprofile:register' %}" class="need-help">Create an account </a>
                </form>
            </div>
            <a href="{% url 'general:contact' %}" class="text-center new-account">Need help? </a><span class="clearfix"></span>
        </div>
    </div>
</div>
<section id="login">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block">
        </div>
      </div>
    </div>
    
  </div>
</section>
{% endblock %}